# Generated by Django 4.2.2 on 2023-06-29 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('xth_pass_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2018)])),
                ('xth_pass_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('secondary_pass_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2020)])),
                ('secondary_pass_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('secondary_pass_subject', models.CharField(choices=[('computer science', 'computer science'), ('bio maths', 'bio maths')], default='computer science', max_length=200)),
                ('degree_pass_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2023)])),
                ('degree_pass_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('degree_subject', models.CharField(choices=[('BCA', 'BCA'), ('Bsc Computer Science', 'Bsc Computer Science'), ('Bsc Physics', 'Bsc Physics'), ('Bsc Maths', 'Bsc Maths'), ('Bsc Chemistry', 'Bsc Chemistry'), ('BVoc IT', 'BVoc IT')], default='BCA', max_length=200)),
                ('course_option1', models.CharField(choices=[('MCA', 'MCA'), ('Mvoc Software Development', 'Mvoc Software Development')], default='MCA', max_length=200)),
                ('course_option2', models.CharField(choices=[('MCA', 'MCA'), ('Mvoc Software Development', 'Mvoc Software Development')], default='Mvoc Software Developmen', max_length=200)),
                ('selected_course', models.CharField(max_length=20, null=True)),
                ('date_of_admission', models.DateField(null=True)),
                ('roll_no', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(max_length=300)),
                ('gurardian', models.CharField(max_length=100)),
                ('guardian_contact_number', models.CharField(max_length=100)),
                ('guardian_email', models.EmailField(max_length=254, null=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_contact_number', models.CharField(max_length=100)),
            ],
        ),
    ]
