# Generated by Django 4.2.2 on 2023-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course_option2',
            field=models.CharField(choices=[('MCA', 'MCA'), ('Mvoc Software Development', 'Mvoc Software Development')], default='Mvoc Software Development', max_length=200),
        ),
    ]
