# Generated by Django 4.2.2 on 2023-06-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_registration_course_option2'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(null=True, upload_to='student_photos'),
        ),
    ]
