# Generated by Django 4.2.2 on 2023-06-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_registration_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('first_semester_exam_fee', models.FloatField(default=None, null=True)),
                ('first_semester_exam_fee_paid_date', models.DateTimeField(default=None, null=True)),
                ('second_semester_exam_fee', models.FloatField(default=None, null=True)),
                ('second_semester_exam_fee_paid_date', models.DateTimeField(default=None, null=True)),
                ('third_semester_exam_fee', models.FloatField(default=None, null=True)),
                ('third_semester_exam_fee_paid_date', models.DateTimeField(default=None, null=True)),
                ('fourth_semester_exam_fee', models.FloatField(default=None, null=True)),
                ('fourth_semester_exam_fee_paid_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, null=True)),
                ('pta_fund', models.FloatField(default=None, null=True)),
                ('first_semester_fee', models.FloatField(default=None, null=True)),
                ('first_semester_fee_paid_date', models.DateTimeField(default=None, null=True)),
                ('second_semester_fee', models.FloatField(default=None, null=True)),
                ('second_semester_fee_paid_date', models.DateTimeField(default=None, null=True)),
                ('third_semester_fee', models.FloatField(default=None, null=True)),
                ('third_semester_fee_paid_date', models.DateTimeField(default=None, null=True)),
                ('fourth_semester_fee', models.FloatField(default=None, null=True)),
                ('fourth_semester_fee_paid_date', models.DateTimeField(default=None, null=True)),
                ('exam_fees', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.examfees')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='fees',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.semesterfees'),
        ),
    ]
