# Generated by Django 4.2.2 on 2023-07-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_examfees_semesterfees_registration_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, max_length=50, null=True)),
                ('semester1', models.FloatField(blank=True, null=True)),
                ('semester2', models.FloatField(blank=True, null=True)),
                ('semester3', models.FloatField(blank=True, null=True)),
                ('semester4', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
