# Generated by Django 4.2.2 on 2023-07-08 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_feepaymentdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fees',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.semesterfees'),
        ),
    ]
